name: comix
channels:
  - cannylab
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=openblas
  - ca-certificates=2020.10.14=0
  - cuda101=1.0=h589bae5_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.10=h5a2b251_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - nomkl=3.0=0
  - numpy-base=1.19.1=py36h75fe3a5_0
  - openblas=0.3.10=0
  - openblas-devel=0.3.10=0
  - openssl=1.1.1h=h7b6447c_0
  - pip=20.0.2=py36_1
  - python=3.6.10=hcf32534_1
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - blessings==1.7
    - cachetools==4.1.0
    - certifi==2020.6.20
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - efficientnet-pytorch==0.7.0
    - filelock==3.0.12
    - gast==0.3.3
    - gdown==3.10.2
    - google-auth==1.13.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - gpustat==0.6.0
    - gputil==1.4.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - imageio==2.9.0
    - joblib==0.15.1
    - kaggle==1.5.6
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.2.0
    - markdown==3.2.1
    - matplotlib==3.3.1
    - networkx==2.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencv-python==4.4.0.42
    - pandas==1.1.5
    - pillow==7.2.0
    - protobuf==3.11.3
    - psutil==5.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - python-dateutil==2.8.1
    - python-slugify==4.0.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.17.2
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - six==1.14.0
    - sklearn==0.0
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - tifffile==2020.9.3
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.45.0
    - urllib3==1.24.3
    - werkzeug==1.0.1
    - wrapt==1.12.1

